server:
  port: 8080
  error:
    include-stacktrace: on_param

# noinspection undefined
file:
  upload-dir: /evdstorage

spring:
  # H2 Client
  h2:
    console:
      enabled: true
      path: /h2
  # H2 Connection
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  # Show SQL
  jpa:
    open-in-view: false

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB

